# Generated by Django 4.1.7 on 2024-04-03 11:54

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='user_app.profile', verbose_name='صاحب')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.PositiveIntegerField(blank=True, null=True, verbose_name='جایگاه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن سوال')),
                ('question_type', models.CharField(choices=[('optional', 'Optional'), ('drop_down', 'Drop Down'), ('sort', 'Sort'), ('text_answer', 'Text Answer'), ('number_answer', 'Number Answer'), ('integer_range', 'Integer Range'), ('integer_selective', 'Integer Selective'), ('picture_field', 'Picture Field'), ('email_field', 'Email Field'), ('link', 'Link'), ('file', 'File'), ('group', 'Group'), ('no_answer', 'No Answer')], editable=False, max_length=50, verbose_name='نوع سوال')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری/عیراجباری')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده/نشده')),
                ('media', models.FileField(blank=True, null=True, upload_to='question_media/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'webm'])], verbose_name='تصویر یا فیلم')),
                ('double_picture_size', models.BooleanField(default=False, verbose_name='اندازه تصویر دو برابر')),
                ('level', models.PositiveIntegerField(choices=[(1, 'آسان'), (2, 'متوسط'), (3, 'سخت'), (0, 'تعیین سطح نشده')], default=0, verbose_name='سطح')),
            ],
            options={
                'ordering': ('placement',),
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('timer', models.DurationField(blank=True, null=True, verbose_name='تایمر')),
                ('previous_button', models.BooleanField(default=False, verbose_name='نمایش دکمه قبلی')),
                ('show_question_in_pages', models.BooleanField(default=True, verbose_name='نشان دادن سوال ها در صفحات مجزا')),
                ('progress_bar', models.BooleanField(default=True, verbose_name='نشان دادن نوار پیشرفت')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='یو یو آی دی')),
                ('show_number', models.BooleanField(default=True, verbose_name='نمایش شماره سوال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('bate_questions', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('is_template', models.BooleanField(default=False, verbose_name='قالب/غیرقالب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question_app.category')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='question_app.folder', verbose_name='پوشه')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='user_app.profile', verbose_name='صاحب')),
                ('price_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='admin_app.pricepack', verbose_name='بسته قیمت')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DropDownQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('multiple_choice', models.BooleanField(default=False, verbose_name='چند انتخابی')),
                ('max_selected_options', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر گزینه انتخابی')),
                ('min_selected_options', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل گزینه انتخابی')),
                ('is_alphabetic_order', models.BooleanField(default=False, verbose_name='مرتب سازی بر اساس حروف الفبا')),
                ('is_random_options', models.BooleanField(default=False, verbose_name='ترتیب تصادفی گزینه ها')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='EmailFieldQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='FileQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('max_volume', models.PositiveIntegerField(default=30, verbose_name='حداکثر حجم')),
                ('volume_unit', models.CharField(choices=[('mb', 'MB'), ('kb', 'KB')], default='mb', max_length=3, verbose_name='واحد حجم')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='IntegerRangeQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('min', models.PositiveIntegerField(choices=[(0, '1'), (1, '0')], default=1, verbose_name='حداقل مقدار')),
                ('max', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مقدار')),
                ('min_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='برچسب چپ')),
                ('mid_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='برچسب وسط')),
                ('max_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='برچسب راست')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='IntegerSelectiveQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('shape', models.CharField(choices=[('H', 'Heart'), ('S', 'Star'), ('L', 'Like'), ('C', 'Check Mark'), ('D', 'Dislike'), ('SM', 'Smile')], default='S', max_length=2, verbose_name='شکل دکمه')),
                ('max', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مقدار')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='LinkQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='NoAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('button_shape', models.CharField(choices=[('sharp', 'Sharp corners'), ('round', 'Round corners'), ('oval', 'Oval')], default='round', max_length=6, verbose_name='شکل دکمه')),
                ('is_solid_button', models.BooleanField(default=False, verbose_name='دکمه تو پر/تو خالی')),
                ('button_text', models.CharField(max_length=100, verbose_name='متن دکمه')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='NumberAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('min', models.IntegerField(blank=True, null=True, verbose_name='حداقل مقدار')),
                ('max', models.IntegerField(blank=True, null=True, verbose_name='حداکثر مقدار')),
                ('accept_negative', models.BooleanField(default=True, verbose_name='جواب می تواند منفی باشد')),
                ('accept_float', models.BooleanField(default=True, verbose_name='جواب می تواند اعشاری باشد')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='OptionalQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('multiple_choice', models.BooleanField(default=False, verbose_name='چند انتخابی')),
                ('additional_options', models.BooleanField(default=False, verbose_name='گزینه های اضافی')),
                ('max_selected_options', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر گزینه انتخابی')),
                ('min_selected_options', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل گزینه انتخابی')),
                ('all_options', models.BooleanField(default=False, verbose_name='انتخاب همه گزینه ها')),
                ('nothing_selected', models.BooleanField(default=False, verbose_name='هیچ کدام')),
                ('other_options', models.BooleanField(default=False, verbose_name='گزینه های دیگر')),
                ('is_vertical', models.BooleanField(default=False, verbose_name='نمایش عمودی گزینه ها')),
                ('is_random_options', models.BooleanField(default=False, verbose_name='ترتیب تصادفی گزینه ها')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='PictureFieldQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='SortQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('is_random_options', models.BooleanField(default=False, verbose_name='ترتیب تصادفی گزینه ها')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='TextAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('answer_template', models.CharField(blank=True, max_length=250, null=True, verbose_name='قالب پاسخ')),
                ('pattern', models.CharField(choices=[('free', 'Free Text'), ('jalali_date', 'Jalali Date'), ('georgian_date', 'Gregorian Date'), ('mobile_number', 'Mobile Number'), ('phone_number', 'Phone Number'), ('number_character', 'Number Character'), ('persian_letters', 'Persian Letters'), ('english_letters', 'English Letters')], default='free', max_length=50, verbose_name='الگوی پاسخ')),
                ('min', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل طول جواب')),
                ('max', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر طول جواب')),
            ],
            bases=('question_app.question',),
        ),
        migrations.CreateModel(
            name='WelcomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('media', models.FileField(blank=True, null=True, upload_to='welcome_page/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'webm'])], verbose_name='تصویر یا فیلم')),
                ('is_solid_button', models.BooleanField(default=False, verbose_name='دکمه تو پر/تو خالی')),
                ('button_text', models.CharField(max_length=100, verbose_name='متن دکمه')),
                ('button_shape', models.CharField(choices=[('sharp', 'Sharp corners'), ('round', 'Round corners'), ('oval', 'Oval')], default='round', max_length=6, verbose_name='شکل دکمه')),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_page', to='question_app.questionnaire', verbose_name='پرسشنامه')),
            ],
        ),
        migrations.CreateModel(
            name='ThanksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('media', models.FileField(blank=True, null=True, upload_to='thanks_page/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'webm'])], verbose_name='تصویر یا فیلم')),
                ('share_link', models.BooleanField(default=False, verbose_name='اشتراک گذاری لینک')),
                ('instagram', models.BooleanField(default=False, verbose_name='اشتراک در اینستاگرام')),
                ('telegram', models.BooleanField(default=False, verbose_name='اشتراک در تلگرام')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='اشتراک در واتساپ')),
                ('eitaa', models.BooleanField(default=False, verbose_name='اشتراک در ایتا')),
                ('sorush', models.BooleanField(default=False, verbose_name='اشتراک در سروش')),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thanks_page', to='question_app.questionnaire', verbose_name='پرسشنامه')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_app.questionnaire', verbose_name='پرسشنامه'),
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخگویی')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_sets', to='user_app.profile')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_sets', to='question_app.questionnaire', verbose_name='پرسشنامه')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True, verbose_name='جواب')),
                ('file', models.FileField(blank=True, null=True, upload_to='answer_file/%Y/%m/%d', verbose_name='فایل')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخگویی')),
                ('level', models.PositiveIntegerField(choices=[(0, 'تعیین نشده'), (1, 'ساده'), (2, 'متوسط'), (3, 'سخت')], default=0, verbose_name='سطح')),
                ('answer_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_app.answerset', verbose_name='دسته جواب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_app.question', verbose_name='سوال')),
            ],
        ),
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='متن گزینه')),
                ('sort_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_app.sortquestion', verbose_name='سوال اولویت دهی')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='question_app.questiongroup', verbose_name='گروه'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='متن گزینه')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره گزینه')),
                ('optional_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_app.optionalquestion', verbose_name='سوال چند گزینه ای ')),
            ],
        ),
        migrations.CreateModel(
            name='DropDownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='متن گزینه')),
                ('drop_down_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_app.dropdownquestion', verbose_name='سوال کشویی')),
            ],
        ),
    ]
