# Generated by Django 4.1.7 on 2023-04-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='question_app.questionnaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='emailanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='fileanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='integerrangeanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='integerselectiveanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='linkanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='numberanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='optionselection',
            name='option',
        ),
        migrations.RemoveField(
            model_name='pictureanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='DropDownSelection',
        ),
        migrations.DeleteModel(
            name='EmailAnswer',
        ),
        migrations.DeleteModel(
            name='FileAnswer',
        ),
        migrations.DeleteModel(
            name='IntegerRangeAnswer',
        ),
        migrations.DeleteModel(
            name='IntegerSelectiveAnswer',
        ),
        migrations.DeleteModel(
            name='LinkAnswer',
        ),
        migrations.DeleteModel(
            name='NumberAnswer',
        ),
        migrations.DeleteModel(
            name='OptionSelection',
        ),
        migrations.DeleteModel(
            name='PictureAnswer',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_app.answerset'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_app.question'),
        ),
    ]
