# Generated by Django 4.2 on 2023-04-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_answer_answerset_remove_emailanswer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanswerquestion',
            name='pattern',
            field=models.CharField(choices=[('free', 'Free Text'), ('jalali_date', 'Jalali Date'), ('gregorian_date', 'Gregorian Date'), ('mobile_number', 'Mobile Number'), ('phone_number', 'Phone Number'), ('number_character', 'Number Character'), ('persian_letters', 'Persian Letters'), ('english_letters', 'English Letters')], default='free', max_length=50),
        ),
    ]
