# Generated by Django 4.1.7 on 2023-04-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0003_textanswerquestion_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='placement',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
