# Generated by Django 4.1.7 on 2023-04-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0005_questiongroup_dropdownquestion_is_alphabetic_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='button_shape',
            field=models.CharField(choices=[('sharp', 'Sharp corners'), ('round', 'Round corners'), ('oval', 'Oval')], default='round', max_length=6),
        ),
    ]
