# Generated by Django 4.1.7 on 2023-04-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0006_alter_questiongroup_button_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_app.question')),
                ('is_random_options', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('question_app.question',),
        ),
        migrations.RemoveField(
            model_name='picturefieldquestion',
            name='answer',
        ),
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('placement', models.PositiveIntegerField()),
                ('sort_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_app.sortquestion')),
            ],
        ),
    ]
